import type { Metadata } from "next";
import { Inter, Space_Mono } from "next/font/google";
import "./globals.css";
import db from "@/lib/supabase/db";
import NextThemeProvider from "@/lib/providers/next-theme-provider";
const inter = Inter({
  weight: ["400", "700"],
  variable: "--font-inter",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  weight: "400",
  variable: "--font-space-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Saas-App for workspaces",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${spaceMono.variable} antialiased`}>
        <NextThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          {children}
        </NextThemeProvider>
      </body>
    </html>
  );
}
